[2021-05-28 14:13:47,571] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /monitor/server/
Traceback (most recent call last):
  File "D:\Projects\django-vue-admin\server\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Projects\django-vue-admin\server\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Projects\django-vue-admin\server\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Projects\django-vue-admin\server\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Projects\django-vue-admin\server\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\Projects\django-vue-admin\server\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\Projects\django-vue-admin\server\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\Projects\django-vue-admin\server\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\Projects\django-vue-admin\server\apps\monitor\views.py", line 28, in get
    print(x)
NameError: name 'x' is not defined
[2021-05-28 14:13:47,575] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /monitor/server/ HTTP/1.1" 500 19278
